repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - "--ignore-words-list"
          - "nd,nam,nin"
          - --skip
          - "poetry.lock"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        name: mypy
        #language: system
        entry: mypy dataplaybook
        types: [python]
        pass_filenames: false
        args:
          - --show-error-codes
          - --config-file
          - pyproject.toml
        additional_dependencies: ["types-requests", "attrs>21"]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry
        language: system
        types: [python]
        pass_filenames: false
        args: [
            "run",
            "pylint",
            "dataplaybook",
            "tests",
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
