name: CI

on: [push, pull_request]

env:
  RUFF_VERSION: 0.9.7
  UV_VERSION: 0.6.2
  TEST_TARGET: "src tests"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          version: ${{ env.RUFF_VERSION }}
      - uses: chartboost/ruff-action@v1
        with:
          args: "format --check"
          version: ${{ env.RUFF_VERSION }}

  pylint:
    name: Check pylint
    needs: [ruff]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Install Requirements
        run: uv sync --frozen --all-extras
      - name: Run Pylint
        run: uv run pylint ${{ env.TEST_TARGET }}

  mypy:
    name: Check mypy
    needs: [ruff]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Install Requirements
        run: uv sync --frozen --all-extras
      - name: Run mypy
        run: uv run mypy --config-file pyproject.toml ${{ env.TEST_TARGET }}

  pytest:
    name: Run tests Python ${{ matrix.python-version }}
    needs: [ruff]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    env:
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Install Requirements
        run: uv sync --frozen --all-extras
      - name: Run tests and generate coverage report
        run: uv run pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: PYTHON
          verbose: true

  release:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    needs: [pytest]
    #if: startsWith(github.ref, 'refs/tags')

    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Setup | Force correct release branch on workflow sha
        run: |
          git checkout -B ${{ github.ref_name }} ${{ github.sha }}

      - name: Action | Semantic Version Release
        id: release
        # Adjust tag with desired version if applicable.
        uses: python-semantic-release/python-semantic-release@v9.21.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: steps.release.outputs.released == 'true'
